language: node_js
node_js:
  - "8.10"
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - ./frontend yarn lint
  - ./backoffice yarn lint
  - ./backend yarn test:check-coverage
after_script:
  - ./backend yarn report-coverage
before_install:
  - ./backend curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - ./backend export PATH=$HOME/.yarn/bin:$PATH